// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fypqdslcsdhihlxincnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cHFkc2xjc2RoaWhseGluY25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjA0NDksImV4cCI6MjA2OTM5NjQ0OX0.f1cDtfMw_L6M3nBmdihhe2_xF-p4Gfazvp19TfCd_lQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});